---
- job:
    name: ansible-role-borgmatic-base
    parent: unittests
    pre-run: tests/playbooks/pre.yaml
    run: tests/playbooks/run.yaml
    post-run:
      - tests/playbooks/post.yaml
      - tests/collect-logs.yaml
    roles:
      - zuul: openstack/ansible-role-borgmatic

# Testing for borgmatic_install_method: pip
- job:
    name: ansible-role-borgmatic
    parent: ansible-role-borgmatic-base

- job:
    name: ansible-role-borgmatic-fedora-latest
    parent: ansible-role-borgmatic
    nodeset: fedora-latest

- job:
    name: ansible-role-borgmatic-ubuntu-bionic
    parent: ansible-role-borgmatic
    nodeset: ubuntu-bionic

# Testing for borgmatic_install_method: git
- job:
    name: ansible-role-borgmatic-src
    parent: ansible-role-borgmatic-base
    vars:
      borgmatic_install_method: git

- job:
    name: ansible-role-borgmatic-src-fedora-latest
    parent: ansible-role-borgmatic-src
    nodeset: fedora-latest

- job:
    name: ansible-role-borgmatic-src-ubuntu-bionic
    parent: ansible-role-borgmatic-src
    nodeset: ubuntu-bionic

- project:
    templates:
      - windmill-backup-jobs-fedora-latest
      - windmill-backup-jobs-bionic
    check:
      jobs:
        - ansible-role-borgmatic-fedora-latest
        - ansible-role-borgmatic-ubuntu-bionic
        - ansible-role-borgmatic-src-fedora-latest
        - ansible-role-borgmatic-src-ubuntu-bionic
        - tox-linters
        - windmill-tox-molecule
    gate:
      jobs:
        - ansible-role-borgmatic-fedora-latest
        - ansible-role-borgmatic-ubuntu-bionic
        - ansible-role-borgmatic-src-fedora-latest
        - ansible-role-borgmatic-src-ubuntu-bionic
        - tox-linters
        - windmill-tox-molecule
